### PR TITLE
Allow an application to return something else than success.

### PR DESCRIPTION
**Pull request by ciechowoj**
As in title.

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
By default I would like the application not having to care about the exit code. Would that be possible?

**Comment by ciechowoj** [comment]
This is of course for dstep. The only way I see is to throw an exception that flies through the `Application` methods and handle it in dstep's main. E.g.

``` D
int main (string[] args)
{
    try
    {
        Application.instance.config = new Configuration;
        return Application.start!Application(args);
    }
    catch (Exception)
    {
        return 1;
    }
}
```

**Comment by jacob-carlborg** [comment]
The point of dstack is to handle some boilerplate code that is required in general for applications. It should of course be possible for other applications than DStep to return a non success exit code.

> The only way I see is to throw an exception that flies through the Application methods and handle it in dstep's main

No, that's pretty ugly. Ideally it would be possible to overload the `run` method on the return type and invoke different run methods depending on which one is implemented. That's of course not possible, unless a template is used.

I'll try to see if I can come up with another solution.

**Comment by ciechowoj** [comment]
Maybe another `run` function that takes an exit status as `ref` arguments and calls the first one by default. One could customize behavior by overriding it.

``` D
void run(ref ExitCode code)
{
    run();
    code = ExitCode.success;
}
```

**Comment by ciechowoj** [comment]
Eh, actually there is no problem at all. I missed the fact that `dstack` already returns failure when there is uncaught exception. 

``` D
int releaseStart ()
    {
        try
            run();

        catch (ApplicationException e)
        {
            println("An error occurred: ", e);
            return ExitCode.failure;
        }

        catch (Throwable e)
        {
            println("An unknown error occurred: ", e);
            throw e;
        }

        return ExitCode.success;
    }
```

I'm not sure why it is only in `release` mode, it would be useful to have it in debug mode too (especially that there is a custom to deliver debug versions of D applications in D community...).

**Comment by jacob-carlborg** [comment]
> Eh, actually there is no problem at all. I missed the fact that dstack already returns failure when there is uncaught exception.

Ah, I thought you wanted to return a non zero exit code without throwing an exception.

> I'm not sure why it is only in release mode, it would be useful to have it in debug mode too (especially that there is a custom to deliver debug versions of D applications in D community...).

The intention was to print the full stack trace of the exception in debug mode, which the runtime is supposed to do. That would aid in developing the application. But actually, it would be better to print the stack trace in verbose mode, or similar.

**Pull request closed without merging**
